import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://exxwin22sum25:5555/")
    page.get_by_role("textbox", name="Enter username").click()
    page.get_by_role("textbox", name="Enter username").fill("Admnistrator")
    page.get_by_role("textbox", name="Enter username").press("Tab")
    page.get_by_role("textbox", name="Enter password").fill("manage")
    page.get_by_role("button", name="Log in").click()
    page.get_by_role("textbox", name="Enter username").click()
    page.get_by_role("textbox", name="Enter username").fill("Admnistrator")
    page.get_by_role("textbox", name="Enter username").press("ArrowLeft")
    page.get_by_role("textbox", name="Enter username").press("ArrowLeft")
    page.get_by_role("textbox", name="Enter username").press("ArrowLeft")
    page.get_by_role("textbox", name="Enter username").press("ArrowLeft")
    page.get_by_role("textbox", name="Enter username").press("ArrowLeft")
    page.get_by_role("textbox", name="Enter username").press("ArrowLeft")
    page.get_by_role("textbox", name="Enter username").press("ArrowRight")
    page.get_by_role("textbox", name="Enter username").fill("Administrator")
    page.get_by_role("button", name="Log in").click()
    page.get_by_test_id("ac.nav.label.server").click()
    page.get_by_test_id("ac.nav.label.ports").click()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="Deny +").nth(2).click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="Set Access Mode to Allow by").click()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="Return to Port List").click()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="Deny +").nth(1).click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="Set Access Mode to Allow by").click()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="Return to Port List").click()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="Deny +").click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="Set Access Mode to Allow by").click()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="Return to Port List").click()
    page.get_by_role("textbox", name="Enter username").click()
    page.get_by_role("textbox", name="Enter username").fill("Administrator")
    page.get_by_role("textbox", name="Enter username").press("Tab")
    page.get_by_role("textbox", name="Enter password").fill("manage")
    page.get_by_role("textbox", name="Enter password").press("Enter")
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="5588", exact=True).click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="Edit HTTPS Port Configuration").click()
    expect(page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="5588", exact=True)).to_be_visible()
    expect(page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="5588", exact=True)).to_be_visible()
    expect(page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="5588", exact=True)).to_be_visible()
    expect(page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="5588", exact=True)).to_be_visible()
    expect(page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="5588", exact=True)).to_be_visible()
    expect(page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="5588", exact=True)).to_be_visible()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("button", name="Save Changes").click()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="5588", exact=True).click()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="Edit HTTPS Port Configuration").click()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("button", name="Save Changes").click()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="5599", exact=True).click()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("link", name="Edit HTTPS Port Configuration").click()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("radio", name="Yes").check()
    page.locator("iframe[name=\"sagDSPFrame\"]").content_frame.get_by_role("button", name="Save Changes").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
